/**
 * 경기도 빵카페 데이터
 *
 * 샘플 데이터입니다. 실제 운영 정보는 각 카페에 확인 후 업데이트하세요.
 * image 필드는 images/ 폴더의 대표 빵 사진을 가리킵니다.
 */
const CAFES = [
  {
    name: "밀밭 베이커리",
    region: "수원시",
    address: "경기 수원시 영통구 광교중앙로 145",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.7,
    badge: "BEST",
    emoji: "🥖",
    image: "images/milbat.jpg",
    menu: ["통밀 캄파뉴", "에그타르트", "크루아상"],
    note: "광교호수공원 근처, 통밀빵으로 유명"
  },
  {
    name: "오븐속 작은빵집",
    region: "성남시",
    address: "경기 성남시 분당구 정자일로 95",
    hours: "화~일 10:00 ~ 21:00 (월 휴무)",
    rating: 4.5,
    emoji: "🍞",
    image: "images/ovenside.jpg",
    menu: ["식빵", "소금빵", "치아바타"],
    note: "정자동 카페거리 골목 안쪽"
  },
  {
    name: "버터하우스",
    region: "성남시",
    address: "경기 성남시 분당구 판교역로 235",
    hours: "매일 08:00 ~ 22:00",
    rating: 4.6,
    badge: "NEW",
    emoji: "🧈",
    image: "images/butterhouse.jpg",
    menu: ["크로플", "버터바", "휘낭시에"],
    note: "판교 알파돔시티, 휘낭시에가 시그니처"
  },
  {
    name: "달콤한 오후",
    region: "용인시",
    address: "경기 용인시 수지구 죽전로 152",
    hours: "수~월 11:00 ~ 21:00 (화 휴무)",
    rating: 4.4,
    emoji: "🥐",
    image: "images/sweet-afternoon.jpg",
    menu: ["크림빵", "단팥빵", "땅콩크림"],
    note: "옛날 추억의 단팥빵 전문"
  },
  {
    name: "프렌치 코너",
    region: "고양시",
    address: "경기 고양시 일산동구 호수로 596",
    hours: "매일 09:30 ~ 22:00",
    rating: 4.6,
    emoji: "🥐",
    image: "images/french-corner.jpg",
    menu: ["크루아상", "팽오쇼콜라", "브리오슈"],
    note: "일산호수공원 바로 옆 프랑스식 빵집"
  },
  {
    name: "노릇노릇",
    region: "안양시",
    address: "경기 안양시 동안구 평촌대로 145",
    hours: "월~토 08:00 ~ 21:00 (일 휴무)",
    rating: 4.3,
    emoji: "🍞",
    image: "images/noreutnoreut.jpg",
    menu: ["우유식빵", "감자빵", "옥수수빵"],
    note: "평촌학원가 직장인 단골집"
  },
  {
    name: "오월의 빵",
    region: "광명시",
    address: "경기 광명시 오리로 854",
    hours: "화~일 10:00 ~ 20:00 (월 휴무)",
    rating: 4.8,
    badge: "BEST",
    emoji: "🌾",
    image: "images/may-bread.jpg",
    menu: ["호밀빵", "캄파뉴", "통밀바게트"],
    note: "천연발효 호밀빵 명가"
  },
  {
    name: "베이크 스튜디오",
    region: "안산시",
    address: "경기 안산시 단원구 광덕대로 178",
    hours: "매일 10:00 ~ 22:00",
    rating: 4.2,
    emoji: "🧁",
    image: "images/bake-studio.jpg",
    menu: ["스콘", "마들렌", "파운드케이크"],
    note: "디저트와 커피가 함께 좋은 곳"
  },
  {
    name: "할머니 빵집",
    region: "의왕시",
    address: "경기 의왕시 오전로 35",
    hours: "월~토 07:00 ~ 19:00 (일 휴무)",
    rating: 4.5,
    emoji: "🥯",
    image: "images/grandma.jpg",
    menu: ["찹쌀도넛", "꽈배기", "단팥도넛"],
    note: "40년 전통 옛날 도넛, 오전부터 줄 섭니다"
  },
  {
    name: "바게트 책방",
    region: "파주시",
    address: "경기 파주시 회동길 145 (헤이리)",
    hours: "수~일 11:00 ~ 19:00 (월·화 휴무)",
    rating: 4.7,
    emoji: "📚",
    image: "images/baguette-books.jpg",
    menu: ["바게트", "치아바타", "리스띠끄"],
    note: "헤이리예술마을 책방 겸 빵집"
  },
  {
    name: "햇살 베이커리",
    region: "남양주시",
    address: "경기 남양주시 다산중앙로 82",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.3,
    emoji: "☀️",
    image: "images/sunlight.jpg",
    menu: ["소금빵", "마늘바게트", "올리브치아바타"],
    note: "다산신도시, 소금빵 입소문"
  },
  {
    name: "동네 빵공장",
    region: "부천시",
    address: "경기 부천시 원미구 부일로 365",
    hours: "화~일 09:00 ~ 21:00 (월 휴무)",
    rating: 4.4,
    emoji: "🏭",
    image: "images/village-factory.jpg",
    menu: ["식빵", "모카번", "베이글"],
    note: "매일 새벽 직접 반죽, 베이글 인기"
  },
  {
    name: "초승달 베이커리",
    region: "화성시",
    address: "경기 화성시 동탄대로 587",
    hours: "매일 10:00 ~ 22:00",
    rating: 4.5,
    badge: "NEW",
    emoji: "🌙",
    image: "images/crescent.jpg",
    menu: ["크루아상", "프레첼", "데니쉬"],
    note: "동탄2 신도시 인기 신생 베이커리"
  },
  {
    name: "보리수 빵집",
    region: "평택시",
    address: "경기 평택시 평남로 1063",
    hours: "월~토 08:00 ~ 20:00 (일 휴무)",
    rating: 4.2,
    emoji: "🌳",
    image: "images/bori-tree.jpg",
    menu: ["보리빵", "흑미식빵", "잡곡스콘"],
    note: "잡곡 위주 건강빵 전문"
  },
  {
    name: "치즈룸",
    region: "김포시",
    address: "경기 김포시 김포한강9로 76",
    hours: "수~월 10:00 ~ 21:00 (화 휴무)",
    rating: 4.6,
    emoji: "🧀",
    image: "images/cheeseroom.jpg",
    menu: ["치즈볼", "고르곤졸라 포카치아", "치즈케이크"],
    note: "치즈 듬뿍 빵 전문점"
  },
  {
    name: "강가의 빵카페",
    region: "양평군",
    address: "경기 양평군 양서면 양수로 117",
    hours: "수~월 10:00 ~ 19:00 (화 휴무)",
    rating: 4.8,
    badge: "BEST",
    emoji: "🏞️",
    image: "images/riverside.jpg",
    menu: ["통밀 사워도", "캄파뉴", "허브 포카치아"],
    note: "두물머리 강뷰, 드라이브 코스"
  },
  {
    name: "구운 마음",
    region: "이천시",
    address: "경기 이천시 부발읍 경충대로 2078",
    hours: "매일 09:00 ~ 20:00",
    rating: 4.3,
    emoji: "❤️",
    image: "images/baked-heart.jpg",
    menu: ["쌀빵", "쌀카스테라", "쌀도넛"],
    note: "이천 햅쌀로 만든 쌀빵 전문"
  },
  {
    name: "포레스트 베이커리",
    region: "가평군",
    address: "경기 가평군 청평면 호반로 1374",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.7,
    emoji: "🌲",
    image: "images/forest.jpg",
    menu: ["통밀 깜빠뉴", "호두 무화과", "잣 스콘"],
    note: "주말 한정 운영, 청평호 근처 숲속 카페"
  },
  {
    name: "단단한 빵",
    region: "오산시",
    address: "경기 오산시 경기대로 244",
    hours: "월~토 09:00 ~ 21:00 (일 휴무)",
    rating: 4.4,
    emoji: "💪",
    image: "images/firm-bread.jpg",
    menu: ["하드 사워도", "호밀 바게트", "씨앗 식빵"],
    note: "단단한 식감의 유럽식 빵 전문"
  },
  {
    name: "구름빵",
    region: "하남시",
    address: "경기 하남시 미사강변중앙로 200",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.5,
    emoji: "☁️",
    image: "images/cloud-bread.jpg",
    menu: ["우유 생크림빵", "솜사탕 식빵", "휘낭시에"],
    note: "미사역 근처, 생크림빵으로 유명"
  },
  {
    name: "고소한 아침",
    region: "광주시",
    address: "경기 광주시 경충대로 1438",
    hours: "화~일 08:00 ~ 19:00 (월 휴무)",
    rating: 4.3,
    emoji: "🌅",
    image: "images/savory-morning.jpg",
    menu: ["우유식빵", "땅콩크림빵", "고구마빵"],
    note: "주말 브런치 메뉴도 운영"
  },
  {
    name: "베이커스 골목",
    region: "시흥시",
    address: "경기 시흥시 정왕대로 28",
    hours: "매일 10:00 ~ 21:00",
    rating: 4.2,
    emoji: "🛍️",
    image: "images/bakers-alley.jpg",
    menu: ["크림치즈베이글", "프레첼", "치아바타 샌드위치"],
    note: "베이글 샌드위치 인기"
  },
  {
    name: "햇귀리 베이커리",
    region: "여주시",
    address: "경기 여주시 세종로 1",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.6,
    emoji: "🌾",
    image: "images/oat-bakery.jpg",
    menu: ["귀리식빵", "통밀 깜빠뉴", "호두빵"],
    note: "여주 한글시장 근처 건강빵 전문"
  },
  {
    name: "별이 빵집",
    region: "포천시",
    address: "경기 포천시 소흘읍 죽엽산로 167",
    hours: "금~일 10:00 ~ 18:00",
    rating: 4.5,
    emoji: "⭐",
    image: "images/star-bakery.jpg",
    menu: ["천연발효 캄파뉴", "허브 치아바타", "잣 휘낭시에"],
    note: "주말 한정, 산속 작은 빵집"
  },
  {
    name: "화서 호밀공방",
    region: "수원시",
    address: "경기 수원시 팔달구 화서문로 38",
    hours: "화~일 09:00 ~ 20:00 (월 휴무)",
    rating: 4.5,
    emoji: "🌾",
    image: "images/hwaseo-rye.jpg",
    menu: ["호밀빵", "통밀 캄파뉴", "호밀 식빵"],
    note: "화서문 근처 호밀 전문 작업실"
  },
  {
    name: "영통 사워도 라보",
    region: "수원시",
    address: "경기 수원시 영통구 효원로 386",
    hours: "수~일 11:00 ~ 21:00 (월·화 휴무)",
    rating: 4.6,
    badge: "NEW",
    emoji: "🧪",
    image: "images/yeongtong-sourdough.jpg",
    menu: ["사워도 식빵", "통밀 사워도", "치아바타"],
    note: "발효 24시간 사워도 전문 라보"
  },
  {
    name: "위례 모닝베이커리",
    region: "성남시",
    address: "경기 성남시 수정구 위례광장로 21",
    hours: "매일 07:00 ~ 21:00",
    rating: 4.4,
    emoji: "🌅",
    image: "images/wirye-morning.jpg",
    menu: ["크루아상", "에그 베이글", "햄치즈 데니쉬"],
    note: "출근길 신선한 모닝 베이커리"
  },
  {
    name: "수지 빵공방",
    region: "용인시",
    address: "경기 용인시 수지구 풍덕천로 87",
    hours: "월~토 09:00 ~ 21:00 (일 휴무)",
    rating: 4.5,
    emoji: "🍞",
    image: "images/suji-bakery.jpg",
    menu: ["우유식빵", "버터롤", "초코크림빵"],
    note: "동네 단골 많은 클래식 빵집"
  },
  {
    name: "처인 화덕 베이커리",
    region: "용인시",
    address: "경기 용인시 처인구 명지로 116",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.7,
    badge: "BEST",
    emoji: "🔥",
    image: "images/cheoin-firewood.jpg",
    menu: ["화덕 깜빠뉴", "포카치아", "장작빵"],
    note: "장작 화덕으로 굽는 유럽식 빵"
  },
  {
    name: "덕양 천연발효소",
    region: "고양시",
    address: "경기 고양시 덕양구 중앙로 633",
    hours: "화~일 10:00 ~ 20:00 (월 휴무)",
    rating: 4.6,
    emoji: "🌿",
    image: "images/deokyang-natural.jpg",
    menu: ["천연발효 식빵", "올리브 깜빠뉴", "허브 포카치아"],
    note: "유기농 밀가루 천연발효 전문"
  },
  {
    name: "행신 베이커리",
    region: "고양시",
    address: "경기 고양시 덕양구 행신로 91",
    hours: "매일 08:00 ~ 22:00",
    rating: 4.3,
    emoji: "🥐",
    image: "images/haengsin-bakery.jpg",
    menu: ["크루아상", "팽오쇼콜라", "데니쉬"],
    note: "행신역 인근, 출근길 인기"
  },
  {
    name: "만안 단팥집",
    region: "안양시",
    address: "경기 안양시 만안구 안양로 268",
    hours: "월~토 08:00 ~ 19:00 (일 휴무)",
    rating: 4.4,
    emoji: "🫘",
    image: "images/manan-anpan.jpg",
    menu: ["단팥빵", "크림단팥", "찰떡단팥"],
    note: "30년 전통 단팥빵 전문점"
  },
  {
    name: "인덕원 베이커리",
    region: "안양시",
    address: "경기 안양시 동안구 관악대로 480",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.2,
    emoji: "🥯",
    image: "images/indeogwon.jpg",
    menu: ["베이글", "프레첼", "치아바타"],
    note: "인덕원역 4번 출구 베이글 전문"
  },
  {
    name: "철산 모닝베이커리",
    region: "광명시",
    address: "경기 광명시 철산로 31",
    hours: "매일 07:00 ~ 21:00",
    rating: 4.3,
    emoji: "🌅",
    image: "images/cheolsan-morning.jpg",
    menu: ["소금빵", "마늘바게트", "에그타르트"],
    note: "철산역 근처 새벽 영업"
  },
  {
    name: "광명동굴 호두빵",
    region: "광명시",
    address: "경기 광명시 가학로85번길 142",
    hours: "수~일 10:00 ~ 18:00 (월·화 휴무)",
    rating: 4.5,
    badge: "NEW",
    emoji: "🌰",
    image: "images/gwangmyeong-walnut.jpg",
    menu: ["호두빵", "호두파이", "호두 휘낭시에"],
    note: "광명동굴 입구, 호두 듬뿍"
  },
  {
    name: "단원 곡물공방",
    region: "안산시",
    address: "경기 안산시 단원구 고잔로 56",
    hours: "화~일 09:00 ~ 20:00 (월 휴무)",
    rating: 4.4,
    emoji: "🌾",
    image: "images/danwon-grain.jpg",
    menu: ["통곡물 식빵", "잡곡 깜빠뉴", "씨앗 스콘"],
    note: "통곡물 위주 건강빵 전문"
  },
  {
    name: "상록수 빵카페",
    region: "안산시",
    address: "경기 안산시 상록구 상록수로 119",
    hours: "매일 10:00 ~ 22:00",
    rating: 4.3,
    emoji: "🌳",
    image: "images/sangnoksu.jpg",
    menu: ["크림치즈 베이글", "샌드위치", "스콘"],
    note: "상록수역, 브런치 메뉴 운영"
  },
  {
    name: "백운호수 호밀집",
    region: "의왕시",
    address: "경기 의왕시 백운로 175",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.7,
    badge: "BEST",
    emoji: "🌾",
    image: "images/baekun-lake.jpg",
    menu: ["호밀 깜빠뉴", "사워도 식빵", "통밀 바게트"],
    note: "백운호수 산책길, 호밀빵 명가"
  },
  {
    name: "부곡 모닝베이커리",
    region: "의왕시",
    address: "경기 의왕시 부곡중앙남2길 18",
    hours: "월~토 07:30 ~ 20:00 (일 휴무)",
    rating: 4.2,
    emoji: "🌅",
    image: "images/bugok-morning.jpg",
    menu: ["소금빵", "크루아상", "크림빵"],
    note: "부곡역 인근 출근길 빵집"
  },
  {
    name: "운정 베이커리",
    region: "파주시",
    address: "경기 파주시 미래로 460",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.4,
    emoji: "🥖",
    image: "images/unjeong-bakery.jpg",
    menu: ["바게트", "치아바타", "올리브 포카치아"],
    note: "운정신도시 클래식 베이커리"
  },
  {
    name: "임진강 호밀공방",
    region: "파주시",
    address: "경기 파주시 문산읍 임진산로 132",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.6,
    emoji: "🌊",
    image: "images/imjin-rye.jpg",
    menu: ["호밀 깜빠뉴", "잡곡 사워도", "호두 무화과"],
    note: "임진강 뷰, 주말 한정 운영"
  },
  {
    name: "별내 호밀공방",
    region: "남양주시",
    address: "경기 남양주시 별내중앙로 23",
    hours: "화~일 10:00 ~ 20:00 (월 휴무)",
    rating: 4.5,
    emoji: "🌾",
    image: "images/byeollae-rye.jpg",
    menu: ["호밀 깜빠뉴", "통밀 식빵", "잡곡 바게트"],
    note: "별내 신도시 호밀빵 전문"
  },
  {
    name: "마석 빵카페",
    region: "남양주시",
    address: "경기 남양주시 화도읍 비룡로 78",
    hours: "수~월 10:00 ~ 21:00 (화 휴무)",
    rating: 4.3,
    emoji: "☕",
    image: "images/maseok-cafe.jpg",
    menu: ["치즈케이크", "스콘", "휘낭시에"],
    note: "마석역 인근, 디저트 함께"
  },
  {
    name: "상동 호두빵",
    region: "부천시",
    address: "경기 부천시 상동로 96",
    hours: "월~토 09:00 ~ 21:00 (일 휴무)",
    rating: 4.4,
    emoji: "🌰",
    image: "images/sangdong-walnut.jpg",
    menu: ["호두빵", "호두 식빵", "호두파이"],
    note: "상동역 근처 호두빵 전문"
  },
  {
    name: "중동 모닝베이커리",
    region: "부천시",
    address: "경기 부천시 원미구 중동로 248",
    hours: "매일 07:00 ~ 22:00",
    rating: 4.2,
    emoji: "🌅",
    image: "images/jungdong-morning.jpg",
    menu: ["소금빵", "에그타르트", "크루아상"],
    note: "중동 신도시, 새벽 영업"
  },
  {
    name: "봉담 베이커리",
    region: "화성시",
    address: "경기 화성시 봉담읍 와우안길 17",
    hours: "화~일 10:00 ~ 20:00 (월 휴무)",
    rating: 4.4,
    emoji: "🥖",
    image: "images/bongdam-bakery.jpg",
    menu: ["바게트", "크루아상", "치아바타"],
    note: "봉담 캠퍼스 인근 인기"
  },
  {
    name: "송산 호밀집",
    region: "화성시",
    address: "경기 화성시 송산면 마도로 1042",
    hours: "수~일 11:00 ~ 19:00 (월·화 휴무)",
    rating: 4.6,
    badge: "NEW",
    emoji: "🌾",
    image: "images/songsan-rye.jpg",
    menu: ["호밀 깜빠뉴", "통밀 사워도", "씨앗 식빵"],
    note: "송산그린시티, 천연발효 호밀빵"
  },
  {
    name: "송탄 모닝빵집",
    region: "평택시",
    address: "경기 평택시 송탄로 109",
    hours: "매일 07:00 ~ 21:00",
    rating: 4.3,
    emoji: "🌅",
    image: "images/songtan-morning.jpg",
    menu: ["크림빵", "단팥빵", "소금빵"],
    note: "송탄역 근처, 출근길 빵집"
  },
  {
    name: "안중 베이커리",
    region: "평택시",
    address: "경기 평택시 안중읍 안현로 134",
    hours: "월~토 09:00 ~ 20:00 (일 휴무)",
    rating: 4.4,
    emoji: "🍞",
    image: "images/anjung-bakery.jpg",
    menu: ["우유식빵", "버터롤", "마늘바게트"],
    note: "안중 시장 인근 동네 빵집"
  },
  {
    name: "구래 호밀공방",
    region: "김포시",
    address: "경기 김포시 김포한강8로 91",
    hours: "화~일 10:00 ~ 20:00 (월 휴무)",
    rating: 4.5,
    emoji: "🌾",
    image: "images/gurae-rye.jpg",
    menu: ["호밀 사워도", "통밀 깜빠뉴", "잡곡 식빵"],
    note: "한강신도시 호밀빵 전문"
  },
  {
    name: "운양 베이커리",
    region: "김포시",
    address: "경기 김포시 김포한강3로 220",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.3,
    emoji: "🥐",
    image: "images/unyang-bakery.jpg",
    menu: ["크루아상", "데니쉬", "프레첼"],
    note: "운양역 옆 인기 베이커리"
  },
  {
    name: "용문 베이커리",
    region: "양평군",
    address: "경기 양평군 용문면 용문산로 25",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.5,
    emoji: "🍞",
    image: "images/yongmun-bakery.jpg",
    menu: ["통밀 식빵", "잡곡 깜빠뉴", "호두빵"],
    note: "용문산 등산로 입구"
  },
  {
    name: "서종 숲속빵집",
    region: "양평군",
    address: "경기 양평군 서종면 북한강로 968",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.7,
    badge: "BEST",
    emoji: "🌲",
    image: "images/seojong-forest.jpg",
    menu: ["사워도 깜빠뉴", "호두 무화과", "잣 스콘"],
    note: "북한강뷰, 주말 한정 운영"
  },
  {
    name: "도자 베이커리",
    region: "이천시",
    address: "경기 이천시 신둔면 도예촌로 81",
    hours: "수~월 10:00 ~ 19:00 (화 휴무)",
    rating: 4.5,
    emoji: "🏺",
    image: "images/doja-bakery.jpg",
    menu: ["쌀 식빵", "쌀 카스테라", "쑥떡빵"],
    note: "도자기 마을 옆, 이천쌀 활용"
  },
  {
    name: "모가 호밀공방",
    region: "이천시",
    address: "경기 이천시 모가면 모가로 372",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.6,
    emoji: "🌾",
    image: "images/moga-rye.jpg",
    menu: ["호밀 사워도", "통밀 깜빠뉴", "씨앗 식빵"],
    note: "모가 한적한 시골길 호밀빵"
  },
  {
    name: "가평 잣마을 베이커리",
    region: "가평군",
    address: "경기 가평군 가평읍 자라섬로 60",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.6,
    emoji: "🌰",
    image: "images/gapyeong-pine.jpg",
    menu: ["잣 스콘", "잣 휘낭시에", "잣크림빵"],
    note: "가평 잣 듬뿍, 자라섬 근처"
  },
  {
    name: "자라섬 호밀공방",
    region: "가평군",
    address: "경기 가평군 가평읍 달전리 14-1",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.7,
    emoji: "🏞️",
    image: "images/jarasum-rye.jpg",
    menu: ["호밀 깜빠뉴", "통밀 사워도", "치아바타"],
    note: "자라섬 캠핑장 인근 숲속 빵집"
  },
  {
    name: "운암 베이커리",
    region: "오산시",
    address: "경기 오산시 운암로 122",
    hours: "월~토 09:00 ~ 21:00 (일 휴무)",
    rating: 4.3,
    emoji: "🥖",
    image: "images/unam-bakery.jpg",
    menu: ["바게트", "치아바타", "포카치아"],
    note: "운암지구 동네 빵집"
  },
  {
    name: "세교 호두빵",
    region: "오산시",
    address: "경기 오산시 세교중앙로 158",
    hours: "매일 09:00 ~ 21:00",
    rating: 4.4,
    emoji: "🌰",
    image: "images/segyo-walnut.jpg",
    menu: ["호두빵", "호두파이", "호두 크림빵"],
    note: "세교신도시, 호두빵 전문"
  },
  {
    name: "덕풍 베이커리",
    region: "하남시",
    address: "경기 하남시 덕풍남로 17",
    hours: "화~일 09:00 ~ 20:00 (월 휴무)",
    rating: 4.4,
    emoji: "🍞",
    image: "images/deokpung-bakery.jpg",
    menu: ["우유식빵", "단팥빵", "크림빵"],
    note: "덕풍시장 인근 클래식 빵집"
  },
  {
    name: "신장 모닝빵집",
    region: "하남시",
    address: "경기 하남시 신장로 86",
    hours: "매일 07:00 ~ 21:00",
    rating: 4.2,
    emoji: "🌅",
    image: "images/sinjang-morning.jpg",
    menu: ["크루아상", "소금빵", "에그타르트"],
    note: "하남시청 인근, 출근길 인기"
  },
  {
    name: "곤지암 베이커리",
    region: "광주시",
    address: "경기 광주시 곤지암읍 곤지암로 23",
    hours: "수~월 10:00 ~ 20:00 (화 휴무)",
    rating: 4.5,
    emoji: "🥐",
    image: "images/gonjiam-bakery.jpg",
    menu: ["크루아상", "데니쉬", "버터바"],
    note: "곤지암 IC 근처, 드라이브 코스"
  },
  {
    name: "오포 호두빵",
    region: "광주시",
    address: "경기 광주시 오포읍 오포로 521",
    hours: "월~토 09:00 ~ 20:00 (일 휴무)",
    rating: 4.4,
    emoji: "🌰",
    image: "images/opo-walnut.jpg",
    menu: ["호두빵", "호두 식빵", "호두 휘낭시에"],
    note: "오포 단독주택가 호두빵 전문"
  },
  {
    name: "배곧 베이커리",
    region: "시흥시",
    address: "경기 시흥시 배곧4로 32",
    hours: "매일 09:00 ~ 22:00",
    rating: 4.4,
    badge: "NEW",
    emoji: "🥖",
    image: "images/baegot-bakery.jpg",
    menu: ["깜빠뉴", "치아바타", "올리브 포카치아"],
    note: "배곧신도시, 신생 베이커리"
  },
  {
    name: "월곶 모닝빵집",
    region: "시흥시",
    address: "경기 시흥시 월곶중앙로 39",
    hours: "화~일 07:00 ~ 20:00 (월 휴무)",
    rating: 4.3,
    emoji: "🌅",
    image: "images/wolgot-morning.jpg",
    menu: ["소금빵", "크림빵", "단팥빵"],
    note: "월곶포구 근처, 새벽 영업"
  },
  {
    name: "신륵사 호두빵",
    region: "여주시",
    address: "경기 여주시 신륵사길 73",
    hours: "수~월 09:00 ~ 18:00 (화 휴무)",
    rating: 4.5,
    emoji: "🌰",
    image: "images/silleuksa-walnut.jpg",
    menu: ["호두빵", "호두파이", "쌀 호두빵"],
    note: "신륵사 입구, 여주 호두 사용"
  },
  {
    name: "능서 호밀공방",
    region: "여주시",
    address: "경기 여주시 능서면 능서로 198",
    hours: "금~일 11:00 ~ 18:00 (평일 휴무)",
    rating: 4.6,
    emoji: "🌾",
    image: "images/neungseo-rye.jpg",
    menu: ["호밀 깜빠뉴", "통밀 사워도", "잡곡 식빵"],
    note: "한적한 시골길, 천연발효 전문"
  },
  {
    name: "산정호수 베이커리",
    region: "포천시",
    address: "경기 포천시 영북면 산정호수로 411",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.5,
    emoji: "🏞️",
    image: "images/sanjeong-lake.jpg",
    menu: ["깜빠뉴", "통밀 식빵", "허브 치아바타"],
    note: "산정호수 둘레길 옆 카페"
  },
  {
    name: "일동 호두빵",
    region: "포천시",
    address: "경기 포천시 일동면 일동로 999",
    hours: "월~토 09:00 ~ 20:00 (일 휴무)",
    rating: 4.3,
    emoji: "🌰",
    image: "images/ildong-walnut.jpg",
    menu: ["호두빵", "호두파이", "호두 크림빵"],
    note: "일동온천 근처, 포천 호두 사용"
  },
  {
    name: "안성맞춤 베이커리",
    region: "안성시",
    address: "경기 안성시 시장길 86",
    hours: "매일 09:00 ~ 21:00",
    rating: 4.5,
    badge: "NEW",
    emoji: "🎯",
    image: "images/anseong-fit.jpg",
    menu: ["크림빵", "단팥빵", "우유식빵"],
    note: "안성시장 옆, 안성맞춤 정성"
  },
  {
    name: "안성팜랜드 호밀공방",
    region: "안성시",
    address: "경기 안성시 공도읍 대신두길 28",
    hours: "수~일 10:00 ~ 19:00 (월·화 휴무)",
    rating: 4.6,
    emoji: "🌾",
    image: "images/anseong-farmland.jpg",
    menu: ["호밀 깜빠뉴", "통밀 사워도", "씨앗 식빵"],
    note: "안성팜랜드 인근, 유기농 호밀"
  },
  {
    name: "죽산 모닝빵집",
    region: "안성시",
    address: "경기 안성시 죽산면 죽산로 200",
    hours: "월~토 07:00 ~ 20:00 (일 휴무)",
    rating: 4.3,
    emoji: "🌅",
    image: "images/juksan-morning.jpg",
    menu: ["소금빵", "크루아상", "에그타르트"],
    note: "죽산면 한적한 길가 빵집"
  }
];
